# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fxcalculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_579c90382cba4d87a9e5814c262016eb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ef5269b9238c41abab0380e76e734436 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_579c90382cba4d87a9e5814c262016eb }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fxcalculator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3902afbe526f4bdbbf6ac340a2ef26f2 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_579c90382cba4d87a9e5814c262016eb }}/appsvc/staticsite:${{ github.sha }}'